### ISSUE TITLE
经验001 单个表单项的校验

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/javascript_work_pro#1]
html代码
``` html

<!DOCTYPE html>
<html>
<head>
<title>单个表单的校验</title>    
<link rel="stylesheet" href="main.css"/>
</head>
<body>
    <div id="content">
    <form>
    <div id="name">
    <label for="input_name">名称</label>
    <input type="text" id="input_name" name="user_name"/>
    <input type="button" id="input_check" name="check" value="验证"/>
    <span id="name_hint">  </span>
    </div>

    </form>
    </div>
    <script type="text/javascript" src="main.js"></script>
</body>
</html>
```

**Comment by Easy-MJ** [comment]
css代码
``` css
* {
    margin: 0;
    padding: 0;
}

#content {
    text-align: center;
    margin:40px auto;
}

#content {
    
}

form {
    width: 600px;
    margin: 30px auto;
    padding: 30px 20px;
    border: solid 1px #999;
    border-radius: 10px;
    font-size: 23px;
    font-weight: bold;
}
input {
    height: 40px;
    font-size:23px;
    border: solid 1px #999;
}

#name label {
    margin-right: 20px;
}

input[type=text] {
    width:250px;
    padding-left: 10px;
}
#input_check {
    margin-left: 10px;
    border-radius: 7px;
    background: #1297FE;
    color: white;
    padding: 0px 15px;
}

#input_check:hover {
    background: #1E45EA;
}

form span {
    display: block;
    font-size: 15px;
    color: #999;
    text-align:left;
    padding-left: 153px;
}
```
