### ISSUE TITLE
经验002 多个表单项的校验

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/javascript_work_pro#2]
html代码
``` html
<!DOCTYPE html>
<html>
<head>
<title>表单<一>单个表单的校验</title>    
<link rel="stylesheet" href="main.css"/>
</head>
<body>
    <div id="content">
    <fieldset>
        <legend>多个表单</legend>
    <table>
        <tr>
            <td><label for="i1">名称</label></td>
            <td><input type="text" id="i1"></input></td>
        </tr>
        <tr>
            <td></td>
            <td class="hint" id="h1"></td>
        </tr>
        <tr>
            <td><label for="i2">密码</label></td>
            <td><input type="password" id="i2"></input></td>
        </tr>
        <tr>
            <td></td>
            <td class="hint" id="h2"></td>
        </tr>
        <tr>
            <td><label for="i3">密码确认</label></td>
            <td><input type="password" id="i3"></input></td>
        </tr>
        <tr>
            <td></td>
            <td class="hint" id="h3"></td>
        </tr>
        <tr>
            <td><label for="i4">邮箱</label></td>
            <td><input type="text" id="i4"></input></td>
        </tr>
        <tr>
            <td></td>
            <td class="hint" id="h4"></td>
        </tr>
        <tr>
            <td><label for="i5">手机</label></td>
            <td><input type="text" id="i5"></input></td>
        </tr>
        <tr>
            <td></td>
            <td class="hint" id="h5"></td>
        </tr>
        <tr>
            <td></td>
            <td><button type="submit" id="submit">提交</button></td>
        </tr>
    </table>
    </fieldset>
    </div>
    <script type="text/javascript" src="main.js"></script>
</body>
</html>
```

**Comment by Easy-MJ** [comment]
css代码
``` css
* {
    margin: 0;
    padding: 0;
}

#content {
    width: 600px;
    margin: 50px auto;
}

form fieldset {
    margin: 10px 10px;
    padding: 20px 20px;
    box-shadow: 2px 2px 4px #ccc;
}

table {
    margin: 0 auto;
}

table td {
    padding: 5px;
}

input {
    width: 300px;
    height: 30px;
}

.hint {
    display: none;
    font-size: 13px;
}

.right {
    border-color: green;
}

.wrong {
    border-color: red;
}

label {
    display: block;
    width: 100%;
    text-align: right;
}

button {
    width: 3.5em;
    height: 1.8em;
    float: right;
    font-size: 18px;
    background: blue;
    color: white;
    border-radius: .5em;
}
```
